name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ“Œ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          echo "ğŸ— This job's status is c."
          ls ${{ github.workspace}}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
    - run: npm ci
    - run: npm test
    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Build Docker Image
      run: |
        docker pull ghcr.io/${{ github.repository }}:latest || :
        docker build -t ghcr.io/${{ github.repository }}:latest . \
          --cache-from ghcr.io/${{ github.repository }}:latest \
          --build-arg VCS_REF=${{ github.sha }} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
    - name: Login to GitHub Package Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
